/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Security-relevant events. Appended to .mimir/runs/<run_id>/audit.jsonl and (for cross-run events) .mimir/audit.jsonl.
 */
export interface AuditEvent {
  schema_version: 1;
  event_id: string;
  kind:
    | "trust_added"
    | "trust_removed"
    | "permission_allow"
    | "permission_ask_approved"
    | "permission_ask_denied"
    | "permission_denied"
    | "override_requested"
    | "override_granted"
    | "override_denied"
    | "filter_trusted"
    | "filter_untrusted"
    | "redaction_applied"
    | "provider_call"
    | "gateway_provider_quarantined"
    | "config_changed"
    | "memory_promoted"
    | "memory_revoked"
    | "drift_initialized"
    | "drift_anomaly"
    | "cost_cap_aborted"
    | "recall_guard_flagged"
    | "gateway_refused"
    | "sufficiency_check_failed"
    | "subagent_spawned"
    | "subagent_completed"
    | "schema_migration_applied";
  at: string;
  run_id?: string | null;
  actor?: "user" | "agent" | "auto_policy" | "ci";
  /**
   * What the event is about (path, target, provider, etc.).
   */
  subject?: string;
  /**
   * Structured details specific to the event kind. Not redacted; do not put secrets here.
   */
  details?: {
    [k: string]: unknown;
  };
}
