/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-category token accounting for a ContextPacket. Each category's value is the number of input tokens that category contributed to the request.
 */
export interface BudgetLedger {
  schema_version: 1;
  packet_id: string;
  categories: {
    system: number;
    task: number;
    acceptance: number;
    rules: number;
    memory: number;
    repo_map: number;
    code_ranges: number;
    editable_files: number;
    tests_logs: number;
    current_diff: number;
    tool_schemas: number;
    tool_outputs: number;
    subagent_summaries: number;
  };
  /**
   * Sum of input-token categories only. Must equal ContextPacket.estimated_input_tokens.
   */
  total: number;
  cap_tokens: number;
  target_tokens: number;
  /**
   * Reserved output window. Not included in total because it is not input context.
   */
  output_reserve_tokens: number;
  /**
   * Reserved slack for local-vs-server count drift. Not included in total because it is not input context.
   */
  count_drift_reserve_tokens: number;
  /**
   * total + output_reserve_tokens + count_drift_reserve_tokens. Must be <= cap_tokens.
   */
  window_total_tokens: number;
  /**
   * target_tokens - total. May be negative if over-target (still under cap).
   */
  slack: number;
  /**
   * Tokens served from provider prompt cache (if applicable).
   */
  cache_hits_tokens?: number;
  cache_misses_tokens?: number;
}
