/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Output of the retrieval pipeline (Stage 4). Input to the packer (Stage 5). Lists all candidates discovered, ranked, and dedup'd, before budget packing decides which become `included` and which become `omitted` in the ContextPacket.
 */
export interface CandidateManifest {
  schema_version: 1;
  manifest_id: string;
  run_id: string;
  /**
   * Path to or hash of the task card this manifest was built for.
   */
  task_card_ref: string;
  /**
   * Ranked candidates. Each conforms to ContextCandidate.schema.json.
   */
  candidates: ContextCandidate[];
  /**
   * @minItems 1
   */
  stages_run: [
    "high_recall_scan" | "structural_expansion" | "semantic_retrieval",
    ...("high_recall_scan" | "structural_expansion" | "semantic_retrieval")[]
  ];
  stage_latency_ms?: {
    high_recall_scan?: number;
    structural_expansion?: number;
    semantic_retrieval?: number;
    [k: string]: unknown;
  };
  elapsed_ms: number;
  candidate_count_pre_dedup?: number;
  candidate_count_post_dedup?: number;
  created_at: string;
}
/**
 * A single candidate emitted by retrieval. Candidates are either packed into the ContextPacket.included list or recorded in ContextPacket.omitted_candidates.
 */
export interface ContextCandidate {
  schema_version: 1;
  path: string;
  ranges?: {
    start: number;
    end: number;
  }[];
  candidate_kind: "full_file" | "symbol_slice" | "line_range";
  reason_code:
    | "direct_user_mention"
    | "failing_test_reference"
    | "symbol_definition"
    | "caller"
    | "callee"
    | "config_dependency"
    | "route_or_schema_link"
    | "git_cochange"
    | "prior_memory_match"
    | "embedding_match"
    | "stack_trace_reference"
    | "manifest_reference";
  score: number;
  /**
   * Normalized feature values [0.0, 1.0] that contributed to the score.
   */
  features: {
    [k: string]: number;
  };
  estimated_tokens: number;
  /**
   * @minItems 1
   */
  discovered_by: [
    "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
    ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
  ];
  source_hash?: string;
}
