/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * A ContextCandidate that did not make it into the packet. Recording these is mandatory: a clean packet that omits required evidence is worse than a slightly larger packet that preserves the decisive dependency.
 */
export type OmittedCandidate = ContextCandidateBase & {
  reason_for_omission:
    | "budget_overflow"
    | "lower_relevance_score"
    | "redundant_with_included"
    | "generated_file_policy"
    | "secret_risk"
    | "large_file_threshold"
    | "untrusted_repo_policy";
  risk?: null | "caller_missing" | "test_missing" | "config_missing" | "schema_missing" | "import_orphan";
  /**
   * Human-readable description of what change in retrieval state would cause this candidate to be included.
   */
  what_would_trigger_inclusion: string;
};

/**
 * The central artifact of a Mimir model call: a hashable, replayable manifest of every file range, evidence card, tool schema, and memory entry sent to a provider. Every provider call originates from one of these.
 */
export interface ContextPacket {
  schema_version: 1;
  /**
   * Stable unique ID for this packet. UUID v4.
   */
  packet_id: string;
  /**
   * SHA-256 of the JCS-canonicalized packet (excluding packet_hash, estimated_input_tokens, authoritative_input_tokens).
   */
  packet_hash: string;
  /**
   * If this packet is a repair-loop delta, the packet_id of its parent.
   */
  parent_packet_id?: string | null;
  /**
   * If parent_packet_id is set, the diff: added/removed candidates and their reasons.
   */
  delta_from_parent?: {
    added?: string[];
    removed?: string[];
  } | null;
  run_id: string;
  task_card: {
    goal: string;
    acceptance_criteria?: string[];
    likely_files?: string[];
    risk_level?: "low" | "medium" | "high";
    expected_test_command?: string | null;
    unknowns?: string[];
    need_for_large_context?: "none" | "possible" | "likely";
    complexity: "tiny" | "standard" | "complex" | "override";
  };
  mode:
    | "ask"
    | "plan"
    | "code"
    | "review"
    | "explain"
    | "subagent_search"
    | "subagent_file_analyst"
    | "subagent_reviewer"
    | "subagent_test_summarizer"
    | "committee_specialist";
  /**
   * Hard input cap for this packet, in tokens.
   */
  cap_tokens: number;
  /**
   * Packer's target. Less than cap_tokens.
   */
  target_tokens: number;
  output_reserve_tokens: number;
  count_drift_reserve_tokens: number;
  /**
   * Provider name, matching a key in providers.yaml.
   */
  provider: string;
  model: string;
  /**
   * Reference (e.g., file path or content-hash) to the ProviderCapabilities snapshot in effect when this packet was built.
   */
  capability_snapshot_ref: string;
  /**
   * Version of the system prompt contract used (see 20-PROMPT-CONTRACT.md).
   */
  prompt_contract_version: number;
  /**
   * PackedSource items: the post-packing projection of selected candidates. See 05-SCHEMAS.md for the asymmetry vs ContextCandidate (no score/features/discovered_by; trace back via candidate_manifest_ref).
   */
  included: {
    path: string;
    ranges: {
      start: number;
      end: number;
    }[];
    candidate_kind: "full_file" | "symbol_slice" | "line_range";
    reason_code:
      | "direct_user_mention"
      | "failing_test_reference"
      | "symbol_definition"
      | "caller"
      | "callee"
      | "config_dependency"
      | "route_or_schema_link"
      | "git_cochange"
      | "prior_memory_match"
      | "embedding_match"
      | "stack_trace_reference"
      | "manifest_reference";
    tokens: number;
    source_hash: string;
    trust_level: "trusted" | "untrusted";
    editable: boolean;
  }[];
  /**
   * Top-N omitted candidates, per OmittedCandidate.schema.json.
   */
  omitted_candidates: OmittedCandidate[];
  /**
   * Tool schemas included in the request, with per-tool token cost.
   */
  tool_schemas: {
    name: string;
    tokens: number;
    deferred?: boolean;
  }[];
  /**
   * ToolResultCard and TestCard refs (paths under .mimir/runs/<run_id>/).
   */
  evidence_cards: {
    kind: "tool_result" | "test";
    path: string;
    tokens?: number;
  }[];
  /**
   * MemoryEntry refs included in this packet (P6+).
   */
  memory_entries: {
    entry_id: string;
    tokens: number;
    confidence?: "provisional" | "validated" | "revoked";
  }[];
  /**
   * Path to the BudgetLedger artifact for this packet.
   */
  budget_ledger_ref: string;
  /**
   * Path to the CandidateManifest used to build this packet. Null only if the packet was constructed without retrieval (e.g., a hand-built fixture).
   */
  candidate_manifest_ref?: string | null;
  /**
   * If this packet was authorized by an override, the OverrideRequest snapshot.
   */
  override?: {
    requested_cap?: number;
    mode?: "burst" | "read_only" | "reviewer" | "migration";
    reason?: string;
    granted_by?: "user" | "auto_after_failures" | "policy";
    granted_at?: string;
  } | null;
  /**
   * Local-tokenizer estimate of the total input tokens for the request built from this packet.
   */
  estimated_input_tokens: number;
  /**
   * Provider server count endpoint result used for policy enforcement, if available. This may still be an estimate per provider documentation.
   */
  authoritative_input_tokens?: number | null;
  count_provenance: "server_authoritative" | "local_estimate_only" | "unavailable";
  /**
   * High-risk omissions flagged by the recall guard (Stage 7).
   */
  recall_guard_flags?: {
    risk: "caller_missing" | "test_missing" | "config_missing" | "schema_missing" | "import_orphan";
    path: string;
    reason: string;
  }[];
  created_at: string;
}
export interface ContextCandidateBase {
  schema_version: 1;
  path: string;
  ranges?: {
    start: number;
    end: number;
  }[];
  candidate_kind: "full_file" | "symbol_slice" | "line_range";
  reason_code:
    | "direct_user_mention"
    | "failing_test_reference"
    | "symbol_definition"
    | "caller"
    | "callee"
    | "config_dependency"
    | "route_or_schema_link"
    | "git_cochange"
    | "prior_memory_match"
    | "embedding_match"
    | "stack_trace_reference"
    | "manifest_reference";
  score: number;
  /**
   * Normalized feature values [0.0, 1.0] that contributed to the score.
   */
  features: {
    [k: string]: number;
  };
  estimated_tokens: number;
  /**
   * @minItems 1
   */
  discovered_by: [
    "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
    ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
  ];
  source_hash?: string;
}
