/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * A single candidate emitted by retrieval. Candidates are either packed into the ContextPacket.included list or recorded in ContextPacket.omitted_candidates.
 */
export interface ContextCandidate {
  schema_version: 1;
  path: string;
  ranges?: {
    start: number;
    end: number;
  }[];
  candidate_kind: "full_file" | "symbol_slice" | "line_range";
  reason_code:
    | "direct_user_mention"
    | "failing_test_reference"
    | "symbol_definition"
    | "caller"
    | "callee"
    | "config_dependency"
    | "route_or_schema_link"
    | "git_cochange"
    | "prior_memory_match"
    | "embedding_match"
    | "stack_trace_reference"
    | "manifest_reference";
  score: number;
  /**
   * Normalized feature values [0.0, 1.0] that contributed to the score.
   */
  features: {
    [k: string]: number;
  };
  estimated_tokens: number;
  /**
   * @minItems 1
   */
  discovered_by: [
    "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
    ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
  ];
  source_hash?: string;
}
/**
 * This interface was referenced by `ContextCandidate`'s JSON-Schema
 * via the `definition` "ContextCandidateBase".
 */
export interface ContextCandidateBase {
  schema_version: 1;
  path: string;
  ranges?: {
    start: number;
    end: number;
  }[];
  candidate_kind: "full_file" | "symbol_slice" | "line_range";
  reason_code:
    | "direct_user_mention"
    | "failing_test_reference"
    | "symbol_definition"
    | "caller"
    | "callee"
    | "config_dependency"
    | "route_or_schema_link"
    | "git_cochange"
    | "prior_memory_match"
    | "embedding_match"
    | "stack_trace_reference"
    | "manifest_reference";
  score: number;
  /**
   * Normalized feature values [0.0, 1.0] that contributed to the score.
   */
  features: {
    [k: string]: number;
  };
  estimated_tokens: number;
  /**
   * @minItems 1
   */
  discovered_by: [
    "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
    ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
  ];
  source_hash?: string;
}
