/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The deterministic planner's intent before retrieval runs. Informational; the packer's actual ContextPacket may diverge based on what retrieval returns.
 */
export interface ContextPlan {
  schema_version: 1;
  plan_id: string;
  run_id: string;
  need_to_inspect: {
    path: string;
    reason: string;
    desired_ranges?: string[];
    [k: string]: unknown;
  }[];
  do_not_load: {
    path: string;
    reason: string;
    [k: string]: unknown;
  }[];
  /**
   * Informational estimate per BudgetLedger category.
   */
  estimated_budget: {
    [k: string]: number;
  };
  created_at: string;
}
