/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * Output of `ProviderAdapter::calibrate`. Records per-payload local-vs-server token-count drift and produces P50/P95/P99 summary statistics that update `ProviderCapabilities.count_drift_*_observed`.
 */
export interface DriftReport {
  schema_version: 1;
  provider: string;
  model: string;
  /**
   * @minItems 1
   */
  samples: [
    {
      local_tokens: number;
      server_tokens: number;
      drift_ratio: number;
      payload_class?: "tiny" | "standard" | "complex";
    },
    ...{
      local_tokens: number;
      server_tokens: number;
      drift_ratio: number;
      payload_class?: "tiny" | "standard" | "complex";
    }[]
  ];
  drift_p50: number;
  drift_p95: number;
  drift_p99: number;
  /**
   * Recommended `count_drift_reserve_tokens` derived from drift_p95 and cap.
   */
  recommended_reserve_tokens?: number;
  ran_at: string;
}
