/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * Structured error returned by every public API. Always present in non-zero-exit responses in JSON output modes.
 */
export interface Error {
  schema_version: 1;
  /**
   * Stable machine-readable identifier. Examples: gateway_over_cap, gateway_uncountable, retrieval_no_candidates, tool_timeout, policy_denied, provider_rate_limited, schema_invalid, io_not_found.
   */
  code: string;
  category: "gateway" | "retrieval" | "index" | "tool" | "policy" | "provider" | "io" | "schema";
  /**
   * Human-readable description.
   */
  message: string;
  /**
   * Nested cause (recursive Error).
   */
  cause?: {} | null;
  retryable: boolean;
  /**
   * Suggested next action for the user.
   */
  user_visible_hint?: string | null;
  /**
   * Arbitrary structured context (file paths, token counts, IDs). Not redacted; do not put secrets here.
   */
  context?: {
    [k: string]: any;
  };
}
