/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * A single eval fixture: prompt + repo + gold ranges + expected tests.
 */
export interface EvalCase {
  schema_version: 1;
  id: string;
  repo_path: string;
  base_commit: string;
  task: string;
  gold: {
    files: string[];
    ranges: {
      path: string;
      start: number;
      end: number;
    }[];
    distractors?: string[];
  };
  expected_tests?: string[];
  allowed_mode: "ask" | "plan" | "code" | "review" | "explain";
  allowed_caps_to_test?: number[];
  /**
   * True if auto-generated by the auto-fixture pipeline.
   */
  generated?: boolean;
}
