/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Result of running an EvalCase in a specific mode and cap.
 */
export interface EvalResult {
  schema_version: 1;
  case_id: string;
  mode: "0-baseline" | "1-cap-only" | "2-rank" | "3-rank-recall" | "4-rank-recall-subagents" | "5-full";
  cap_tokens: number;
  model?: string;
  provider?: string;
  metrics: {
    file_recall: number;
    range_recall: number;
    precision: number;
    tokens_per_useful_line?: number;
    critical_omission_count: number;
    cap_compliance: boolean;
    token_count_agreement_p95?: number;
    packet_build_latency_ms?: number;
    retrieval_latency_ms?: number;
    repo_map_refresh_latency_ms?: number;
    e2e_latency_ms: number;
    tokens_in_total: number;
    tokens_out_total: number;
    cost_usd_total: number;
    repair_turns?: number;
    override_used?: boolean;
    outcome?: null | "tests_pass" | "tests_fail" | "aborted_cost" | "aborted_repair" | "aborted_policy";
    total_cost_to_success?: number | null;
    index_cache_hit_rate?: number | null;
    prompt_cache_hit_rate?: number | null;
  };
  packet_id?: string;
  run_id?: string;
  ran_at: string;
}
