/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * Required return shape for every subagent (search, file-analyst, reviewer, test-summarizer). Subagents never return free-form prose to the supervisor; they return this structured summary with cited evidence.
 */
export interface EvidenceSummary {
  schema_version: 1;
  summary_id: string;
  subagent_kind: "search" | "file_analyst_deterministic" | "file_analyst_llm" | "reviewer" | "test_summarizer";
  /**
   * The supervisor's run_id.
   */
  parent_run_id: string;
  subagent_run_id?: string;
  subagent_packet_id?: string;
  /**
   * The bounded task the subagent was given.
   */
  task: string;
  files_inspected?: string[];
  important_symbols?: string[];
  /**
   * Cited findings. Every claim has at least one file/range reference.
   */
  findings: {
    claim: string;
    /**
     * @minItems 1
     */
    evidence: [
      {
        path: string;
        ranges: {
          start: number;
          end: number;
        }[];
      },
      ...{
        path: string;
        ranges: {
          start: number;
          end: number;
        }[];
      }[]
    ];
  }[];
  /**
   * Files/ranges the supervisor's next packet should include.
   */
  recommended_parent_inclusions?: {
    path: string;
    ranges?: any[];
    reason: string;
  }[];
  confidence: "high" | "medium" | "low";
  unknowns: string[];
  do_not_assume?: string[];
  ran_at: string;
}
