/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * This interface was referenced by `ExecutablePatchPlan`'s JSON-Schema
 * via the `definition` "patch_step".
 */
export type PatchStep =
  | {
      action: "line_range";
      path: string;
      start_line: number;
      end_line: number;
      content: string;
    }
  | {
      action: "unified_diff";
      path: string;
      diff: string;
    }
  | {
      action: "whole_file";
      path: string;
      content: string;
    }
  | {
      action: "create";
      path: string;
      content: string;
    }
  | {
      action: "delete";
      path: string;
    }
  | {
      action: "move";
      from: string;
      to: string;
    };

/**
 * The executable patch recipe paired with PatchPlan metadata in code-mode runs. PatchPlan explains the edit; ExecutablePatchPlan is the payload Mimir may apply after safety validation.
 */
export interface ExecutablePatchPlan {
  schema_version: 1;
  plan_id: string;
  packet_id: string;
  /**
   * @minItems 1
   */
  steps: [PatchStep, ...PatchStep[]];
}
