declare module "AuditEvent" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Security-relevant events. Appended to .mimir/runs/<run_id>/audit.jsonl and (for cross-run events) .mimir/audit.jsonl.
     */
    export interface AuditEvent {
        schema_version: 1;
        event_id: string;
        kind: "trust_added" | "trust_removed" | "permission_allow" | "permission_ask_approved" | "permission_ask_denied" | "permission_denied" | "override_requested" | "override_granted" | "override_denied" | "filter_trusted" | "filter_untrusted" | "redaction_applied" | "provider_call" | "gateway_provider_quarantined" | "config_changed" | "memory_promoted" | "memory_revoked" | "drift_initialized" | "drift_anomaly" | "cost_cap_aborted" | "recall_guard_flagged" | "gateway_refused" | "sufficiency_check_failed" | "subagent_spawned" | "subagent_completed" | "schema_migration_applied";
        at: string;
        run_id?: string | null;
        actor?: "user" | "agent" | "auto_policy" | "ci";
        /**
         * What the event is about (path, target, provider, etc.).
         */
        subject?: string;
        /**
         * Structured details specific to the event kind. Not redacted; do not put secrets here.
         */
        details?: {
            [k: string]: any;
        };
    }
}
declare module "BudgetLedger" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Per-category token accounting for a ContextPacket. Each category's value is the number of input tokens that category contributed to the request.
     */
    export interface BudgetLedger {
        schema_version: 1;
        packet_id: string;
        categories: {
            system: number;
            task: number;
            acceptance: number;
            rules: number;
            memory: number;
            repo_map: number;
            code_ranges: number;
            editable_files: number;
            tests_logs: number;
            current_diff: number;
            tool_schemas: number;
            tool_outputs: number;
            subagent_summaries: number;
        };
        /**
         * Sum of input-token categories only. Must equal ContextPacket.estimated_input_tokens.
         */
        total: number;
        cap_tokens: number;
        target_tokens: number;
        /**
         * Reserved output window. Not included in total because it is not input context.
         */
        output_reserve_tokens: number;
        /**
         * Reserved slack for local-vs-server count drift. Not included in total because it is not input context.
         */
        count_drift_reserve_tokens: number;
        /**
         * total + output_reserve_tokens + count_drift_reserve_tokens. Must be <= cap_tokens.
         */
        window_total_tokens: number;
        /**
         * target_tokens - total. May be negative if over-target (still under cap).
         */
        slack: number;
        /**
         * Tokens served from provider prompt cache (if applicable).
         */
        cache_hits_tokens?: number;
        cache_misses_tokens?: number;
    }
}
declare module "CandidateManifest" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Output of the retrieval pipeline (Stage 4). Input to the packer (Stage 5). Lists all candidates discovered, ranked, and dedup'd, before budget packing decides which become `included` and which become `omitted` in the ContextPacket.
     */
    export interface CandidateManifest {
        schema_version: 1;
        manifest_id: string;
        run_id: string;
        /**
         * Path to or hash of the task card this manifest was built for.
         */
        task_card_ref: string;
        /**
         * Ranked candidates. Each conforms to ContextCandidate.schema.json.
         */
        candidates: ContextCandidate[];
        /**
         * @minItems 1
         */
        stages_run: [
            "high_recall_scan" | "structural_expansion" | "semantic_retrieval",
            ...("high_recall_scan" | "structural_expansion" | "semantic_retrieval")[]
        ];
        stage_latency_ms?: {
            high_recall_scan?: number;
            structural_expansion?: number;
            semantic_retrieval?: number;
        };
        elapsed_ms: number;
        candidate_count_pre_dedup?: number;
        candidate_count_post_dedup?: number;
        created_at: string;
    }
    /**
     * A single candidate emitted by retrieval. Candidates are either packed into the ContextPacket.included list or recorded in ContextPacket.omitted_candidates.
     */
    export interface ContextCandidate {
        schema_version: 1;
        path: string;
        ranges?: {
            start: number;
            end: number;
        }[];
        candidate_kind: "full_file" | "symbol_slice" | "line_range";
        reason_code: "direct_user_mention" | "failing_test_reference" | "symbol_definition" | "caller" | "callee" | "config_dependency" | "route_or_schema_link" | "git_cochange" | "prior_memory_match" | "embedding_match" | "stack_trace_reference" | "manifest_reference";
        score: number;
        /**
         * Normalized feature values [0.0, 1.0] that contributed to the score.
         */
        features: {
            [k: string]: number;
        };
        estimated_tokens: number;
        /**
         * @minItems 1
         */
        discovered_by: [
            "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
            ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
        ];
        source_hash?: string;
    }
}
declare module "ContextCandidate" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * A single candidate emitted by retrieval. Candidates are either packed into the ContextPacket.included list or recorded in ContextPacket.omitted_candidates.
     */
    export interface ContextCandidate {
        schema_version: 1;
        path: string;
        ranges?: {
            start: number;
            end: number;
        }[];
        candidate_kind: "full_file" | "symbol_slice" | "line_range";
        reason_code: "direct_user_mention" | "failing_test_reference" | "symbol_definition" | "caller" | "callee" | "config_dependency" | "route_or_schema_link" | "git_cochange" | "prior_memory_match" | "embedding_match" | "stack_trace_reference" | "manifest_reference";
        score: number;
        /**
         * Normalized feature values [0.0, 1.0] that contributed to the score.
         */
        features: {
            [k: string]: number;
        };
        estimated_tokens: number;
        /**
         * @minItems 1
         */
        discovered_by: [
            "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
            ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
        ];
        source_hash?: string;
    }
    /**
     * This interface was referenced by `ContextCandidate`'s JSON-Schema
     * via the `definition` "ContextCandidateBase".
     */
    export interface ContextCandidateBase {
        schema_version: 1;
        path: string;
        ranges?: {
            start: number;
            end: number;
        }[];
        candidate_kind: "full_file" | "symbol_slice" | "line_range";
        reason_code: "direct_user_mention" | "failing_test_reference" | "symbol_definition" | "caller" | "callee" | "config_dependency" | "route_or_schema_link" | "git_cochange" | "prior_memory_match" | "embedding_match" | "stack_trace_reference" | "manifest_reference";
        score: number;
        /**
         * Normalized feature values [0.0, 1.0] that contributed to the score.
         */
        features: {
            [k: string]: number;
        };
        estimated_tokens: number;
        /**
         * @minItems 1
         */
        discovered_by: [
            "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
            ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
        ];
        source_hash?: string;
    }
}
declare module "ContextPacket" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * A ContextCandidate that did not make it into the packet. Recording these is mandatory: a clean packet that omits required evidence is worse than a slightly larger packet that preserves the decisive dependency.
     */
    export type OmittedCandidate = ContextCandidateBase & {
        reason_for_omission: "budget_overflow" | "lower_relevance_score" | "redundant_with_included" | "generated_file_policy" | "secret_risk" | "large_file_threshold" | "untrusted_repo_policy";
        risk?: null | "caller_missing" | "test_missing" | "config_missing" | "schema_missing" | "import_orphan";
        /**
         * Human-readable description of what change in retrieval state would cause this candidate to be included.
         */
        what_would_trigger_inclusion: string;
    };
    /**
     * The central artifact of a Mimir model call: a hashable, replayable manifest of every file range, evidence card, tool schema, and memory entry sent to a provider. Every provider call originates from one of these.
     */
    export interface ContextPacket {
        schema_version: 1;
        /**
         * Stable unique ID for this packet. UUID v4.
         */
        packet_id: string;
        /**
         * SHA-256 of the JCS-canonicalized packet (excluding packet_hash, estimated_input_tokens, authoritative_input_tokens).
         */
        packet_hash: string;
        /**
         * If this packet is a repair-loop delta, the packet_id of its parent.
         */
        parent_packet_id?: string | null;
        /**
         * If parent_packet_id is set, the diff: added/removed candidates and their reasons.
         */
        delta_from_parent?: {
            added?: string[];
            removed?: string[];
        } | null;
        run_id: string;
        task_card: {
            goal: string;
            acceptance_criteria?: string[];
            likely_files?: string[];
            risk_level?: "low" | "medium" | "high";
            expected_test_command?: string | null;
            unknowns?: string[];
            need_for_large_context?: "none" | "possible" | "likely";
            complexity: "tiny" | "standard" | "complex" | "override";
        };
        mode: "ask" | "plan" | "code" | "review" | "explain" | "subagent_search" | "subagent_file_analyst" | "subagent_reviewer" | "subagent_test_summarizer" | "committee_specialist";
        /**
         * Hard input cap for this packet, in tokens.
         */
        cap_tokens: number;
        /**
         * Packer's target. Less than cap_tokens.
         */
        target_tokens: number;
        output_reserve_tokens: number;
        count_drift_reserve_tokens: number;
        /**
         * Provider name, matching a key in providers.yaml.
         */
        provider: string;
        model: string;
        /**
         * Reference (e.g., file path or content-hash) to the ProviderCapabilities snapshot in effect when this packet was built.
         */
        capability_snapshot_ref: string;
        /**
         * Version of the system prompt contract used (see 20-PROMPT-CONTRACT.md).
         */
        prompt_contract_version: number;
        /**
         * PackedSource items: the post-packing projection of selected candidates. See 05-SCHEMAS.md for the asymmetry vs ContextCandidate (no score/features/discovered_by; trace back via candidate_manifest_ref).
         */
        included: {
            path: string;
            ranges: {
                start: number;
                end: number;
            }[];
            candidate_kind: "full_file" | "symbol_slice" | "line_range";
            reason_code: "direct_user_mention" | "failing_test_reference" | "symbol_definition" | "caller" | "callee" | "config_dependency" | "route_or_schema_link" | "git_cochange" | "prior_memory_match" | "embedding_match" | "stack_trace_reference" | "manifest_reference";
            tokens: number;
            source_hash: string;
            trust_level: "trusted" | "untrusted";
            editable: boolean;
        }[];
        /**
         * Top-N omitted candidates, per OmittedCandidate.schema.json.
         */
        omitted_candidates: OmittedCandidate[];
        /**
         * Tool schemas included in the request, with per-tool token cost.
         */
        tool_schemas: {
            name: string;
            tokens: number;
            deferred?: boolean;
        }[];
        /**
         * ToolResultCard and TestCard refs (paths under .mimir/runs/<run_id>/).
         */
        evidence_cards: {
            kind: "tool_result" | "test";
            path: string;
            tokens?: number;
        }[];
        /**
         * MemoryEntry refs included in this packet (P6+).
         */
        memory_entries: {
            entry_id: string;
            tokens: number;
            confidence?: "provisional" | "validated" | "revoked";
        }[];
        /**
         * Path to the BudgetLedger artifact for this packet.
         */
        budget_ledger_ref: string;
        /**
         * Path to the CandidateManifest used to build this packet. Null only if the packet was constructed without retrieval (e.g., a hand-built fixture).
         */
        candidate_manifest_ref?: string | null;
        /**
         * If this packet was authorized by an override, the OverrideRequest snapshot.
         */
        override?: {
            requested_cap?: number;
            mode?: "burst" | "read_only" | "reviewer" | "migration";
            reason?: string;
            granted_by?: "user" | "auto_after_failures" | "policy";
            granted_at?: string;
        } | null;
        /**
         * Local-tokenizer estimate of the total input tokens for the request built from this packet.
         */
        estimated_input_tokens: number;
        /**
         * Provider server count endpoint result used for policy enforcement, if available. This may still be an estimate per provider documentation.
         */
        authoritative_input_tokens?: number | null;
        count_provenance: "server_authoritative" | "local_estimate_only" | "unavailable";
        /**
         * High-risk omissions flagged by the recall guard (Stage 7).
         */
        recall_guard_flags?: {
            risk: "caller_missing" | "test_missing" | "config_missing" | "schema_missing" | "import_orphan";
            path: string;
            reason: string;
        }[];
        created_at: string;
    }
    export interface ContextCandidateBase {
        schema_version: 1;
        path: string;
        ranges?: {
            start: number;
            end: number;
        }[];
        candidate_kind: "full_file" | "symbol_slice" | "line_range";
        reason_code: "direct_user_mention" | "failing_test_reference" | "symbol_definition" | "caller" | "callee" | "config_dependency" | "route_or_schema_link" | "git_cochange" | "prior_memory_match" | "embedding_match" | "stack_trace_reference" | "manifest_reference";
        score: number;
        /**
         * Normalized feature values [0.0, 1.0] that contributed to the score.
         */
        features: {
            [k: string]: number;
        };
        estimated_tokens: number;
        /**
         * @minItems 1
         */
        discovered_by: [
            "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
            ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
        ];
        source_hash?: string;
    }
}
declare module "ContextPlan" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * The deterministic planner's intent before retrieval runs. Informational; the packer's actual ContextPacket may diverge based on what retrieval returns.
     */
    export interface ContextPlan {
        schema_version: 1;
        plan_id: string;
        run_id: string;
        need_to_inspect: {
            path: string;
            reason: string;
            desired_ranges?: string[];
        }[];
        do_not_load: {
            path: string;
            reason: string;
        }[];
        /**
         * Informational estimate per BudgetLedger category.
         */
        estimated_budget: {
            [k: string]: number;
        };
        created_at: string;
    }
}
declare module "DriftReport" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Output of `ProviderAdapter::calibrate`. Records per-payload local-vs-server token-count drift and produces P50/P95/P99 summary statistics that update `ProviderCapabilities.count_drift_*_observed`.
     */
    export interface DriftReport {
        schema_version: 1;
        provider: string;
        model: string;
        /**
         * @minItems 1
         */
        samples: [
            {
                local_tokens: number;
                server_tokens: number;
                drift_ratio: number;
                payload_class?: "tiny" | "standard" | "complex";
            },
            ...{
                local_tokens: number;
                server_tokens: number;
                drift_ratio: number;
                payload_class?: "tiny" | "standard" | "complex";
            }[]
        ];
        drift_p50: number;
        drift_p95: number;
        drift_p99: number;
        /**
         * Recommended `count_drift_reserve_tokens` derived from drift_p95 and cap.
         */
        recommended_reserve_tokens?: number;
        ran_at: string;
    }
}
declare module "Error" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Structured error returned by every public API. Always present in non-zero-exit responses in JSON output modes.
     */
    export interface Error {
        schema_version: 1;
        /**
         * Stable machine-readable identifier. Examples: gateway_over_cap, gateway_uncountable, retrieval_no_candidates, tool_timeout, policy_denied, provider_rate_limited, schema_invalid, io_not_found.
         */
        code: string;
        category: "gateway" | "retrieval" | "index" | "tool" | "policy" | "provider" | "io" | "schema";
        /**
         * Human-readable description.
         */
        message: string;
        /**
         * Nested cause (recursive Error).
         */
        cause?: {} | null;
        retryable: boolean;
        /**
         * Suggested next action for the user.
         */
        user_visible_hint?: string | null;
        /**
         * Arbitrary structured context (file paths, token counts, IDs). Not redacted; do not put secrets here.
         */
        context?: {
            [k: string]: any;
        };
    }
}
declare module "EvalCase" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * A single eval fixture: prompt + repo + gold ranges + expected tests.
     */
    export interface EvalCase {
        schema_version: 1;
        id: string;
        repo_path: string;
        base_commit: string;
        task: string;
        gold: {
            files: string[];
            ranges: {
                path: string;
                start: number;
                end: number;
            }[];
            distractors?: string[];
        };
        expected_tests?: string[];
        allowed_mode: "ask" | "plan" | "code" | "review" | "explain";
        allowed_caps_to_test?: number[];
        /**
         * True if auto-generated by the auto-fixture pipeline.
         */
        generated?: boolean;
    }
}
declare module "EvalResult" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Result of running an EvalCase in a specific mode and cap.
     */
    export interface EvalResult {
        schema_version: 1;
        case_id: string;
        mode: "0-baseline" | "1-cap-only" | "2-rank" | "3-rank-recall" | "4-rank-recall-subagents" | "5-full";
        cap_tokens: number;
        model?: string;
        provider?: string;
        metrics: {
            file_recall: number;
            range_recall: number;
            precision: number;
            tokens_per_useful_line?: number;
            critical_omission_count: number;
            cap_compliance: boolean;
            token_count_agreement_p95?: number;
            packet_build_latency_ms?: number;
            retrieval_latency_ms?: number;
            repo_map_refresh_latency_ms?: number;
            e2e_latency_ms: number;
            tokens_in_total: number;
            tokens_out_total: number;
            cost_usd_total: number;
            repair_turns?: number;
            override_used?: boolean;
            outcome?: null | "tests_pass" | "tests_fail" | "aborted_cost" | "aborted_repair" | "aborted_policy";
            total_cost_to_success?: number | null;
            index_cache_hit_rate?: number | null;
            prompt_cache_hit_rate?: number | null;
        };
        packet_id?: string;
        run_id?: string;
        ran_at: string;
    }
}
declare module "EvidenceSummary" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Required return shape for every subagent (search, file-analyst, reviewer, test-summarizer). Subagents never return free-form prose to the supervisor; they return this structured summary with cited evidence.
     */
    export interface EvidenceSummary {
        schema_version: 1;
        summary_id: string;
        subagent_kind: "search" | "file_analyst_deterministic" | "file_analyst_llm" | "reviewer" | "test_summarizer";
        /**
         * The supervisor's run_id.
         */
        parent_run_id: string;
        subagent_run_id?: string;
        subagent_packet_id?: string;
        /**
         * The bounded task the subagent was given.
         */
        task: string;
        files_inspected?: string[];
        important_symbols?: string[];
        /**
         * Cited findings. Every claim has at least one file/range reference.
         */
        findings: {
            claim: string;
            /**
             * @minItems 1
             */
            evidence: [
                {
                    path: string;
                    ranges: {
                        start: number;
                        end: number;
                    }[];
                },
                ...{
                    path: string;
                    ranges: {
                        start: number;
                        end: number;
                    }[];
                }[]
            ];
        }[];
        /**
         * Files/ranges the supervisor's next packet should include.
         */
        recommended_parent_inclusions?: {
            path: string;
            ranges?: any[];
            reason: string;
        }[];
        confidence: "high" | "medium" | "low";
        unknowns: string[];
        do_not_assume?: string[];
        ran_at: string;
    }
}
declare module "ExecutablePatchPlan" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * This interface was referenced by `ExecutablePatchPlan`'s JSON-Schema
     * via the `definition` "patch_step".
     */
    export type PatchStep = {
        action: "line_range";
        path: string;
        start_line: number;
        end_line: number;
        content: string;
    } | {
        action: "unified_diff";
        path: string;
        diff: string;
    } | {
        action: "whole_file";
        path: string;
        content: string;
    } | {
        action: "create";
        path: string;
        content: string;
    } | {
        action: "delete";
        path: string;
    } | {
        action: "move";
        from: string;
        to: string;
    };
    /**
     * The executable patch recipe paired with PatchPlan metadata in code-mode runs. PatchPlan explains the edit; ExecutablePatchPlan is the payload Mimir may apply after safety validation.
     */
    export interface ExecutablePatchPlan {
        schema_version: 1;
        plan_id: string;
        packet_id: string;
        /**
         * @minItems 1
         */
        steps: [PatchStep, ...PatchStep[]];
    }
}
declare module "MemoryEntry" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * A durable lesson with source, confidence, scope, and freshness metadata. Earned through verification (see 14-LEARNING-LAYER.md). Memory is retrieved into packets only in Phase 6+.
     */
    export interface MemoryEntry {
        schema_version: 1;
        entry_id: string;
        kind: "project" | "experience" | "error" | "symbol";
        body: string;
        /**
         * @minItems 1
         */
        source_evidence: [
            {
                kind: "run" | "commit" | "file_hash" | "test_card" | "user_correction";
                ref: string;
            },
            ...{
                kind: "run" | "commit" | "file_hash" | "test_card" | "user_correction";
                ref: string;
            }[]
        ];
        confidence: "provisional" | "validated" | "revoked";
        /**
         * Composite score from MemoryDecisionEngine. Null until P6.
         */
        promotion_score?: number | null;
        /**
         * Score components (severity, recurrence, success_rate, task_relevance, token_savings).
         */
        promotion_breakdown?: {
            severity_score?: number;
            recurrence_score?: number;
            success_rate_score?: number;
            task_relevance_score?: number;
            token_savings_score?: number;
            total?: number;
        } | null;
        scope: "private" | "repo_shared" | "global";
        /**
         * If false, the entry stays local and is never included in a packet sent to a provider.
         */
        safe_to_send: boolean;
        created_at: string;
        last_verified_at?: string | null;
        staleness_policy?: {
            max_age_days?: number | null;
            auto_revoke_after_failures?: number | null;
        };
        retrieval_tags: string[];
        /**
         * If this entry was imported from another tool's sessions, the source.
         */
        imported_from?: {
            tool?: "claude-code" | "codex" | "aider" | "mimir";
            session_id?: string;
        } | null;
    }
}
declare module "OmittedCandidate" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * A ContextCandidate that did not make it into the packet. Recording these is mandatory: a clean packet that omits required evidence is worse than a slightly larger packet that preserves the decisive dependency.
     */
    export type OmittedCandidate = ContextCandidateBase & {
        reason_for_omission: "budget_overflow" | "lower_relevance_score" | "redundant_with_included" | "generated_file_policy" | "secret_risk" | "large_file_threshold" | "untrusted_repo_policy";
        risk?: null | "caller_missing" | "test_missing" | "config_missing" | "schema_missing" | "import_orphan";
        /**
         * Human-readable description of what change in retrieval state would cause this candidate to be included.
         */
        what_would_trigger_inclusion: string;
    };
    export interface ContextCandidateBase {
        schema_version: 1;
        path: string;
        ranges?: {
            start: number;
            end: number;
        }[];
        candidate_kind: "full_file" | "symbol_slice" | "line_range";
        reason_code: "direct_user_mention" | "failing_test_reference" | "symbol_definition" | "caller" | "callee" | "config_dependency" | "route_or_schema_link" | "git_cochange" | "prior_memory_match" | "embedding_match" | "stack_trace_reference" | "manifest_reference";
        score: number;
        /**
         * Normalized feature values [0.0, 1.0] that contributed to the score.
         */
        features: {
            [k: string]: number;
        };
        estimated_tokens: number;
        /**
         * @minItems 1
         */
        discovered_by: [
            "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
            ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
        ];
        source_hash?: string;
    }
}
declare module "OverrideRequest" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Logged justification for an above-default cap. Required for any call exceeding ContextPolicy.hard_input_cap_tokens.
     */
    export interface OverrideRequest {
        schema_version: 1;
        request_id: string;
        requested_cap: 128000 | 256000 | 1000000;
        mode: "burst" | "read_only" | "reviewer" | "migration";
        reason: string;
        evidence_already_inspected?: {
            path?: string;
            ranges?: any[];
        }[];
        missing_context?: string[];
        expected_benefit?: string;
        alternatives_attempted?: ("subagent_summary" | "symbol_slicing" | "additional_retrieval" | "test_narrowing" | "none")[];
        requested_at: string;
        granted?: boolean | null;
        granted_by?: null | "user" | "auto_after_failures" | "policy";
        granted_at?: string | null;
        denied_reason?: string | null;
    }
}
declare module "PatchPlan" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * The editor's plan before any file write. The editable_target_set is enforced: the editor cannot write to files outside this set.
     */
    export interface PatchPlan {
        schema_version: 1;
        plan_id: string;
        packet_id: string;
        files_to_edit: {
            path: string;
            edit_kind: "ast_replace" | "line_range_replace" | "unified_diff" | "whole_file_rewrite";
            ranges?: {
                start?: number;
                end?: number;
            }[];
            expected_new_content_hash?: string | null;
        }[];
        /**
         * Authorized files. Equals or is a subset of ContextPacket.included items with editable=true.
         */
        editable_target_set: string[];
        reasoning_per_edit: {
            path: string;
            rationale: string;
            /**
             * What evidence would show this edit is wrong?
             */
            disproving_evidence?: string;
        }[];
        tests_to_run: string[];
        risks: string[];
        what_needs_more_context?: string[];
    }
}
declare module "PlanArtifact" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * The persisted implementation-plan artifact written by `mimir plan`. This is intentionally separate from PatchPlan, which is code-mode patch metadata.
     */
    export interface PlanArtifact {
        schema_version: 1;
        run_id: string;
        packet_id: string;
        packet_hash: string;
        provider: string;
        model: string;
        task: string;
        editable_target_set: string[];
        steps: string[];
        risks: string[];
        files_likely_affected: string[];
        tests_to_run: string[];
        assumptions: string[];
        /**
         * Redacted provider prose preserved only when structured JSON parsing failed.
         */
        raw_response?: string;
    }
}
declare module "ProviderCapabilities" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Per-provider, per-model capability snapshot. Loaded at startup; validated by `mimir providers doctor`. The gateway refuses calls if the packet's capability_snapshot does not match the current registry entry.
     */
    export interface ProviderCapabilities {
        schema_version: 1;
        provider: string;
        models: {
            [k: string]: {
                max_context_tokens: number;
                max_input_tokens: number;
                max_output_tokens: number;
                output_reserve_tokens: number;
                counts_system_tokens: boolean;
                counts_tool_schemas: boolean;
                counts_tool_results: boolean;
                counts_reasoning_tokens: boolean;
                supports_server_token_count: boolean;
                supports_prompt_cache: boolean;
                overflow_behavior: "validation_error" | "stop_reason" | "truncation" | "unknown";
                pricing: {
                    input_per_million: number;
                    output_per_million: number;
                    cache_write_per_million?: number;
                    cache_read_per_million?: number;
                };
                count_drift_p50_observed?: number | null;
                count_drift_p95_observed?: number | null;
                count_drift_p99_observed?: number | null;
                drift_calibrated_at?: string | null;
                /**
                 * If non-null, the eval-suite-derived recommended cap for this model.
                 */
                recommended_cap_tokens?: number | null;
            };
        };
    }
}
declare module "ProviderCapabilitiesList" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Provider capability snapshots returned by provider-list APIs such as workspace/providers.
     */
    export interface ProviderCapabilitiesList {
        schema_version: 1;
        /**
         * @minItems 1
         */
        providers: [ProviderCapabilities, ...ProviderCapabilities[]];
    }
    /**
     * Per-provider, per-model capability snapshot. Loaded at startup; validated by `mimir providers doctor`. The gateway refuses calls if the packet's capability_snapshot does not match the current registry entry.
     */
    export interface ProviderCapabilities {
        schema_version: 1;
        provider: string;
        models: {
            [k: string]: {
                max_context_tokens: number;
                max_input_tokens: number;
                max_output_tokens: number;
                output_reserve_tokens: number;
                counts_system_tokens: boolean;
                counts_tool_schemas: boolean;
                counts_tool_results: boolean;
                counts_reasoning_tokens: boolean;
                supports_server_token_count: boolean;
                supports_prompt_cache: boolean;
                overflow_behavior: "validation_error" | "stop_reason" | "truncation" | "unknown";
                pricing: {
                    input_per_million: number;
                    output_per_million: number;
                    cache_write_per_million?: number;
                    cache_read_per_million?: number;
                };
                count_drift_p50_observed?: number | null;
                count_drift_p95_observed?: number | null;
                count_drift_p99_observed?: number | null;
                drift_calibrated_at?: string | null;
                /**
                 * If non-null, the eval-suite-derived recommended cap for this model.
                 */
                recommended_cap_tokens?: number | null;
            };
        };
    }
}
declare module "RetryPolicy" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Backoff and retryable-code configuration used by the provider gateway and tool runtime.
     */
    export interface RetryPolicy {
        schema_version: 1;
        max_attempts: number;
        initial_backoff_ms: number;
        max_backoff_ms: number;
        jitter: number;
        retryable_codes: ("provider_rate_limited" | "provider_overloaded" | "provider_timeout" | "provider_connection_reset" | "provider_internal_error" | "provider_stream_disconnected")[];
    }
}
declare module "ReviewResult" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Output of the fresh-context reviewer (Phase J of the workflow). Produced by single-reviewer and committee modes. The reviewer sees only the diff, changed source ranges, test cards, and high-risk omitted candidates — not the editor's prior reasoning.
     */
    export interface ReviewResult {
        schema_version: 1;
        review_id: string;
        /**
         * The reviewer packet's ID (not the editor's).
         */
        packet_id: string;
        /**
         * The run_id of the editor work being reviewed.
         */
        editor_run_id?: string;
        verdict: "accept" | "revise" | "reject";
        findings: {
            finding_id: string;
            severity: "critical" | "high" | "medium" | "low" | "info";
            category: "correctness" | "security" | "error_handling" | "concurrency" | "test_coverage" | "test_impact" | "docs_drift" | "api_change" | "performance" | "pressure" | "policy";
            summary: string;
            evidence?: {
                path: string;
                ranges: {
                    start: number;
                    end: number;
                }[];
            }[];
            /**
             * If committee mode, which specialists raised this finding.
             */
            specialists?: ("correctness_security" | "error_handling_concurrency" | "test_impact_coverage" | "docs_api_impact" | "pressure")[];
            /**
             * If true, this finding blocks acceptance regardless of verdict.
             */
            blocking?: boolean;
        }[];
        risks?: string[];
        /**
         * Areas where the reviewer cannot reach a conclusion due to missing evidence.
         */
        coverage_concerns?: {
            concern: string;
            what_would_resolve: string;
        }[];
        committee_mode?: boolean;
        ran_at: string;
    }
}
declare module "TestCard" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Structured replacement for raw test logs. Generated by parsing the test runner output.
     */
    export interface TestCard {
        schema_version: 1;
        card_id: string;
        command: string;
        framework: "pytest" | "vitest" | "jest" | "mocha" | "cargo_test" | "go_test" | "unknown";
        passed: number;
        failed: number;
        skipped: number;
        duration_ms: number;
        top_failure?: {
            test_name?: string;
            message?: string;
            file_path?: string | null;
            line_number?: number | null;
        } | null;
        /**
         * Top frames of the first failure's stack trace.
         */
        stack_top?: string[];
        suspected_files?: string[];
        log_artifact_path: string;
    }
}
declare module "ToolResultCard" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * Structured replacement for raw command output. The card enters the packet; the raw output is stored as an artifact under .mimir/runs/<run_id>/artifacts/.
     */
    export interface ToolResultCard {
        schema_version: 1;
        card_id: string;
        command: string;
        cwd: string;
        safety_class: "READ" | "LOCAL_VERIFY" | "MUTATE" | "DANGEROUS";
        timeout_ms: number;
        exit_code: number;
        duration_ms: number;
        /**
         * Capped, filtered preview.
         */
        stdout_preview: string;
        stderr_preview: string;
        /**
         * Path under .mimir/runs/<run_id>/artifacts/ for the full stdout.
         */
        stdout_artifact_path?: string | null;
        stderr_artifact_path?: string | null;
        stdout_original_size_bytes?: number;
        stderr_original_size_bytes?: number;
        /**
         * File paths detected in the output that may be relevant for follow-up retrieval.
         */
        detected_file_refs?: string[];
        detected_test_refs?: string[];
        estimated_tokens: number;
        inclusion_policy: "always_full" | "preview_only" | "summary_only" | "exclude_from_packet";
        /**
         * Names of declarative filters that ran on this output.
         */
        filters_applied?: string[];
    }
}
declare module "TraceSpan" {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run npm run generate to regenerate this file.
     */
    /**
     * OpenTelemetry-shaped span emitted by the telemetry crate. Stored as JSONL under .mimir/runs/<run_id>/trace.spans.jsonl. Never exported over the network unless an explicit endpoint is configured.
     */
    export interface TraceSpan {
        schema_version: 1;
        span_id: string;
        trace_id?: string;
        parent_id?: string | null;
        name: string;
        kind?: "internal" | "client" | "server" | "producer" | "consumer";
        /**
         * Unix microseconds.
         */
        start_us: number;
        end_us: number;
        /**
         * Attributes. Keep keys snake_case. No secrets.
         */
        attrs?: {
            [k: string]: any;
        };
        events?: {
            at_us: number;
            name: string;
            attrs?: {
                [k: string]: any;
            };
        }[];
        status?: {
            code?: "unset" | "ok" | "error";
            message?: string | null;
        };
    }
}
