/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * A durable lesson with source, confidence, scope, and freshness metadata. Earned through verification (see 14-LEARNING-LAYER.md). Memory is retrieved into packets only in Phase 6+.
 */
export interface MemoryEntry {
  schema_version: 1;
  entry_id: string;
  kind: "project" | "experience" | "error" | "symbol";
  body: string;
  /**
   * @minItems 1
   */
  source_evidence: [
    {
      kind: "run" | "commit" | "file_hash" | "test_card" | "user_correction";
      ref: string;
    },
    ...{
      kind: "run" | "commit" | "file_hash" | "test_card" | "user_correction";
      ref: string;
    }[]
  ];
  confidence: "provisional" | "validated" | "revoked";
  /**
   * Composite score from MemoryDecisionEngine. Null until P6.
   */
  promotion_score?: number | null;
  /**
   * Score components (severity, recurrence, success_rate, task_relevance, token_savings).
   */
  promotion_breakdown?: {
    severity_score?: number;
    recurrence_score?: number;
    success_rate_score?: number;
    task_relevance_score?: number;
    token_savings_score?: number;
    total?: number;
  } | null;
  scope: "private" | "repo_shared" | "global";
  /**
   * If false, the entry stays local and is never included in a packet sent to a provider.
   */
  safe_to_send: boolean;
  created_at: string;
  last_verified_at?: string | null;
  staleness_policy?: {
    max_age_days?: number | null;
    auto_revoke_after_failures?: number | null;
  };
  retrieval_tags: string[];
  /**
   * If this entry was imported from another tool's sessions, the source.
   */
  imported_from?: {
    tool?: "claude-code" | "codex" | "aider" | "mimir";
    session_id?: string;
  } | null;
}
