/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A ContextCandidate that did not make it into the packet. Recording these is mandatory: a clean packet that omits required evidence is worse than a slightly larger packet that preserves the decisive dependency.
 */
export type OmittedCandidate = ContextCandidateBase & {
  reason_for_omission:
    | "budget_overflow"
    | "lower_relevance_score"
    | "redundant_with_included"
    | "generated_file_policy"
    | "secret_risk"
    | "large_file_threshold"
    | "untrusted_repo_policy";
  risk?: null | "caller_missing" | "test_missing" | "config_missing" | "schema_missing" | "import_orphan";
  /**
   * Human-readable description of what change in retrieval state would cause this candidate to be included.
   */
  what_would_trigger_inclusion: string;
  [k: string]: unknown;
};

export interface ContextCandidateBase {
  schema_version: 1;
  path: string;
  ranges?: {
    start: number;
    end: number;
  }[];
  candidate_kind: "full_file" | "symbol_slice" | "line_range";
  reason_code:
    | "direct_user_mention"
    | "failing_test_reference"
    | "symbol_definition"
    | "caller"
    | "callee"
    | "config_dependency"
    | "route_or_schema_link"
    | "git_cochange"
    | "prior_memory_match"
    | "embedding_match"
    | "stack_trace_reference"
    | "manifest_reference";
  score: number;
  /**
   * Normalized feature values [0.0, 1.0] that contributed to the score.
   */
  features: {
    [k: string]: number;
  };
  estimated_tokens: number;
  /**
   * @minItems 1
   */
  discovered_by: [
    "rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory",
    ...("rg" | "ast" | "lsp" | "git_cochange" | "embedding" | "manifest" | "memory")[]
  ];
  source_hash?: string;
  [k: string]: unknown;
}
