/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * Logged justification for an above-default cap. Required for any call exceeding ContextPolicy.hard_input_cap_tokens.
 */
export interface OverrideRequest {
  schema_version: 1;
  request_id: string;
  requested_cap: 128000 | 256000 | 1000000;
  mode: "burst" | "read_only" | "reviewer" | "migration";
  reason: string;
  evidence_already_inspected?: {
    path?: string;
    ranges?: any[];
  }[];
  missing_context?: string[];
  expected_benefit?: string;
  alternatives_attempted?: (
    | "subagent_summary"
    | "symbol_slicing"
    | "additional_retrieval"
    | "test_narrowing"
    | "none"
  )[];
  requested_at: string;
  granted?: boolean | null;
  granted_by?: null | "user" | "auto_after_failures" | "policy";
  granted_at?: string | null;
  denied_reason?: string | null;
}
