/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * Recorded grant of an above-default cap override. Written when an OverrideRequest is approved or auto-granted after N failed attempts. Paired with an override_granted audit event.
 */
export interface OverrideGrant {
  schema_version: 1;
  grant_id: string;
  request_id: string;
  run_id: string;
  granted_cap: number;
  reason: string;
  granted_by: "auto_after_failures" | "user" | "policy";
  prior_failures: number;
  auto_grant_after: number;
  granted_at: string;
}
