/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The editor's plan before any file write. The editable_target_set is enforced: the editor cannot write to files outside this set.
 */
export interface PatchPlan {
  schema_version: 1;
  plan_id: string;
  packet_id: string;
  files_to_edit: {
    path: string;
    edit_kind: "ast_replace" | "line_range_replace" | "unified_diff" | "whole_file_rewrite";
    ranges?: {
      start?: number;
      end?: number;
      [k: string]: unknown;
    }[];
    expected_new_content_hash?: string | null;
    [k: string]: unknown;
  }[];
  /**
   * Authorized files. Equals or is a subset of ContextPacket.included items with editable=true.
   */
  editable_target_set: string[];
  reasoning_per_edit: {
    path: string;
    rationale: string;
    /**
     * What evidence would show this edit is wrong?
     */
    disproving_evidence?: string;
    [k: string]: unknown;
  }[];
  tests_to_run: string[];
  risks: string[];
  what_needs_more_context?: string[];
}
