/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */

/**
 * The persisted implementation-plan artifact written by `mimir plan`. This is intentionally separate from PatchPlan, which is code-mode patch metadata.
 */
export interface PlanArtifact {
  schema_version: 1;
  run_id: string;
  packet_id: string;
  packet_hash: string;
  provider: string;
  model: string;
  task: string;
  editable_target_set: string[];
  steps: string[];
  risks: string[];
  files_likely_affected: string[];
  tests_to_run: string[];
  assumptions: string[];
  /**
   * Redacted provider prose preserved only when structured JSON parsing failed.
   */
  raw_response?: string;
}
