/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-provider, per-model capability snapshot. Loaded at startup; validated by `mimir providers doctor`. The gateway refuses calls if the packet's capability_snapshot does not match the current registry entry.
 */
export interface ProviderCapabilities {
  schema_version: 1;
  provider: string;
  models: {
    [k: string]: {
      max_context_tokens: number;
      max_input_tokens: number;
      max_output_tokens: number;
      output_reserve_tokens: number;
      counts_system_tokens: boolean;
      counts_tool_schemas: boolean;
      counts_tool_results: boolean;
      counts_reasoning_tokens: boolean;
      supports_server_token_count: boolean;
      supports_prompt_cache: boolean;
      overflow_behavior: "validation_error" | "stop_reason" | "truncation" | "unknown";
      pricing: {
        input_per_million: number;
        output_per_million: number;
        cache_write_per_million?: number;
        cache_read_per_million?: number;
        [k: string]: unknown;
      };
      count_drift_p50_observed?: number | null;
      count_drift_p95_observed?: number | null;
      count_drift_p99_observed?: number | null;
      drift_calibrated_at?: string | null;
      /**
       * If non-null, the eval-suite-derived recommended cap for this model.
       */
      recommended_cap_tokens?: number | null;
    };
  };
}
