/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Backoff and retryable-code configuration used by the provider gateway and tool runtime.
 */
export interface RetryPolicy {
  schema_version: 1;
  max_attempts: number;
  initial_backoff_ms: number;
  max_backoff_ms: number;
  jitter: number;
  retryable_codes: (
    | "provider_rate_limited"
    | "provider_overloaded"
    | "provider_timeout"
    | "provider_connection_reset"
    | "provider_internal_error"
    | "provider_stream_disconnected"
  )[];
}
