/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Output of the fresh-context reviewer (Phase J of the workflow). Produced by single-reviewer and committee modes. The reviewer sees only the diff, changed source ranges, test cards, and high-risk omitted candidates — not the editor's prior reasoning.
 */
export interface ReviewResult {
  schema_version: 1;
  review_id: string;
  /**
   * The reviewer packet's ID (not the editor's).
   */
  packet_id: string;
  /**
   * The run_id of the editor work being reviewed.
   */
  editor_run_id?: string;
  verdict: "accept" | "revise" | "reject";
  findings: {
    finding_id: string;
    severity: "critical" | "high" | "medium" | "low" | "info";
    category:
      | "correctness"
      | "security"
      | "error_handling"
      | "concurrency"
      | "test_coverage"
      | "test_impact"
      | "docs_drift"
      | "api_change"
      | "performance"
      | "pressure"
      | "policy";
    summary: string;
    evidence?: {
      path: string;
      ranges: {
        start: number;
        end: number;
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    /**
     * If committee mode, which specialists raised this finding.
     */
    specialists?: (
      | "correctness_security"
      | "error_handling_concurrency"
      | "test_impact_coverage"
      | "docs_api_impact"
      | "pressure"
    )[];
    /**
     * If true, this finding blocks acceptance regardless of verdict.
     */
    blocking?: boolean;
    [k: string]: unknown;
  }[];
  risks?: string[];
  /**
   * Areas where the reviewer cannot reach a conclusion due to missing evidence.
   */
  coverage_concerns?: {
    concern: string;
    what_would_resolve: string;
    [k: string]: unknown;
  }[];
  committee_mode?: boolean;
  ran_at: string;
}
