/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Structured replacement for raw test logs. Generated by parsing the test runner output.
 */
export interface TestCard {
  schema_version: 1;
  card_id: string;
  command: string;
  framework: "pytest" | "vitest" | "jest" | "mocha" | "cargo_test" | "go_test" | "unknown";
  passed: number;
  failed: number;
  skipped: number;
  duration_ms: number;
  top_failure?: {
    test_name?: string;
    message?: string;
    file_path?: string | null;
    line_number?: number | null;
    [k: string]: unknown;
  } | null;
  /**
   * Top frames of the first failure's stack trace.
   */
  stack_top?: string[];
  suspected_files?: string[];
  log_artifact_path: string;
}
