/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Structured replacement for raw command output. The card enters the packet; the raw output is stored as an artifact under .mimir/runs/<run_id>/artifacts/.
 */
export interface ToolResultCard {
  schema_version: 1;
  card_id: string;
  command: string;
  cwd: string;
  safety_class: "READ" | "LOCAL_VERIFY" | "MUTATE" | "DANGEROUS";
  timeout_ms: number;
  exit_code: number;
  duration_ms: number;
  /**
   * Capped, filtered preview.
   */
  stdout_preview: string;
  stderr_preview: string;
  /**
   * Path under .mimir/runs/<run_id>/artifacts/ for the full stdout.
   */
  stdout_artifact_path?: string | null;
  stderr_artifact_path?: string | null;
  stdout_original_size_bytes?: number;
  stderr_original_size_bytes?: number;
  /**
   * File paths detected in the output that may be relevant for follow-up retrieval.
   */
  detected_file_refs?: string[];
  detected_test_refs?: string[];
  estimated_tokens: number;
  inclusion_policy: "always_full" | "preview_only" | "summary_only" | "exclude_from_packet";
  /**
   * Names of declarative filters that ran on this output.
   */
  filters_applied?: string[];
}
