/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * OpenTelemetry-shaped span emitted by the telemetry crate. Stored as JSONL under .mimir/runs/<run_id>/trace.spans.jsonl. Never exported over the network unless an explicit endpoint is configured.
 */
export interface TraceSpan {
  schema_version: 1;
  span_id: string;
  trace_id?: string;
  parent_id?: string | null;
  name: string;
  kind?: "internal" | "client" | "server" | "producer" | "consumer";
  /**
   * Unix microseconds.
   */
  start_us: number;
  end_us: number;
  /**
   * Attributes. Keep keys snake_case. No secrets.
   */
  attrs?: {
    [k: string]: unknown;
  };
  events?: {
    at_us: number;
    name: string;
    attrs?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  status?: {
    code?: "unset" | "ok" | "error";
    message?: string | null;
    [k: string]: unknown;
  };
}
