[package]
name = "mimir-security"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
mimir-schemas = { path = "../mimir-schemas" }
regex = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
