#!/usr/bin/env node
import { compileFromFile } from "json-schema-to-typescript";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const sdkRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(sdkRoot, "../..");
const schemaRoot = join(repoRoot, "schemas");
const checkMode = process.argv.includes("--check");

const schemaFiles = readdirSync(schemaRoot)
  .filter((name) => name.endsWith(".schema.json"))
  .sort();
const schemas = schemaFiles.map((name) => name.slice(0, -".schema.json".length));

const bannerComment = `/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run npm run generate to regenerate this file.
 */`;

const style = {
  bracketSpacing: true,
  printWidth: 120,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "none",
  useTabs: false,
};

const rewriteRefs = (schemaText) => schemaText.replaceAll("https://mimir.dev/schemas/", "./");

const normalize = (text) => text.replace(/\r\n/g, "\n").trimEnd() + "\n";

const tempSchemaRoot = mkdtempSync(join(tmpdir(), "mimir-sdk-schemas-"));

try {
  for (const schemaFile of schemaFiles) {
    const source = join(schemaRoot, schemaFile);
    const rewritten = rewriteRefs(readFileSync(source, "utf8"));
    writeFileSync(join(tempSchemaRoot, basename(source)), rewritten);
  }

  const failures = [];

  for (const schema of schemas) {
    const output = normalize(
      await compileFromFile(join(tempSchemaRoot, `${schema}.schema.json`), {
        additionalProperties: false,
        bannerComment,
        cwd: `${tempSchemaRoot}/`,
        declareExternallyReferenced: true,
        style,
        unknownAny: false,
        unreachableDefinitions: true,
      }),
    );
    const target = join(sdkRoot, `${schema}.ts`);

    if (checkMode) {
      const current = normalize(readFileSync(target, "utf8"));
      if (current !== output) {
        failures.push(`${schema}.ts is out of date; run npm run generate`);
      }
    } else {
      writeFileSync(target, output);
    }
  }

  if (failures.length > 0) {
    console.error(failures.map((failure) => `- ${failure}`).join("\n"));
    process.exit(1);
  }

  console.log(
    checkMode
      ? "Generated SDK schema types are up to date."
      : `Generated SDK schema types: ${schemas.map((schema) => `${schema}.ts`).join(", ")}`,
  );
} finally {
  rmSync(tempSchemaRoot, { force: true, recursive: true });
}
